import * as THREE from 'three';

export const LOCOMOTION_CONSTANTS = {
	SNAP_TURN_ANGLE_MIN: (Math.PI / 180) * 45,
	SNAP_TURN_ANGLE_MAX: (Math.PI / 180) * 135,
	SNAP_TURN_VALUE_MIN: 0.95,
	SNAP_TURN_LEFT_QUAT: new THREE.Quaternion(0, 0.3826834, 0, 0.9238795),
	SNAP_TURN_RIGHT_QUAT: new THREE.Quaternion(0, -0.3826834, 0, 0.9238795),
	TELEPORT_ANGLE_MIN: (Math.PI / 180) * 135,
	TELEPORT_ANGLE_MAX: (Math.PI / 180) * 180,
	TELEPORT_VALUE_MIN: 0.95,
	JOYSTICK_STATE: {
		DISENGAGED: 0,
		LEFT: 1,
		RIGHT: 2,
		BACK: 3,
	},
	MOVEMENT_SPEED: 2.0,
};

export const ASSET_URLS = {
	AVATAR: {
		BROWN_BEAR: 'assets/brown-bear.glb',
	},
};

export const RTC_CONSTANTS = {
	MAX_BUFFER_SIZE: 5,
	RETRY_INTERVAL: 0.05,
	HEADER_LENGTH: 4,
	SECURE_MESSAGE_HEADER: 'SMSG',
	SECURE_ACK_HEADER: 'SACK',
	DEVICE_TRANSFORM_HEADER: 'DVTF',
	OBJECT_DATA_HEADER: 'OBJD',
	OBJECT_SYNC_INTERVAL: 0.25,
};
